export const ServerData = {
    "vendor_search": [
        {
            "data": [
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Houston",
                    "t": "City",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Thousand Oaks",
                    "t": "City",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Spotsylvania Courthouse",
                    "t": "City",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Mulhouse",
                    "t": "City",
                    "i": 0
                }
            ],
            "t": "City"
        },
        {
            "data": [
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "House of Fraser - Manchester",
                    "t": "Mall",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Houston Center",
                    "t": "Mall",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Houston Galleria",
                    "t": "Mall",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Houston Pavilions",
                    "t": "Mall",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Houston Premium Outlets ",
                    "t": "Mall",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Lighthouse Place Premium Outlets ",
                    "t": "Mall",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Pier A Harbor House",
                    "t": "Mall",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Soho Beach House",
                    "t": "Mall",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Tanger Outlets In Galveston / Houston",
                    "t": "Mall",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "The Lakes at Thousand Oaks",
                    "t": "Mall",
                    "i": 0
                }
            ],
            "t": "Mall"
        },
        {
            "data": [
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "White House/ Black Market",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Foot Locker/House of Hoop",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Warehouse Bar & Grille",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Soho House New York",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "The Rittenhouse Hotel",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Original Pancake House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Sweet Pea's Public House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Steamer’s The Grillhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Barrel House Tavern ",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "House of Blues",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "The Chicago Lighthouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Ruth's Chris Steak House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Hugo's Frog Bar & Fish House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "House Of Smoke",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Trail House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "The Breukelen Coffee House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Brickhouse BBQ",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Biltmore Carriage House Gift Shop",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Strip House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Flagler Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Robert's Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Tone House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Del Frisco's Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "The Royce Wood Fired Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Beach House Half Moon Bay",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Bourbon House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "White House|Black Market",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Men's Wearhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Yardhouse Restaurant",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "EMERIL'S NEW ORLEANS FISH HOUSE",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "AJ’s Steak House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "The House Of Shields",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Politics & Prose Bookstore and Coffeehouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Smokehouse Live",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "DSW Designer Shoe Warehouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "ShopHouse ",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Inkwell Coffeehouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "White House Tavern",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Vail Chophouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Claudia's Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "BRIC Arts | Media House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "BLT Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "McCoy's Public House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Outback Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "BJ's Restaurant & Brewhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Potter Stewart U.S. Courthouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "The Ale House Columbia",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "GiGi's Playhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "McGrath's Fish House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Texas Roadhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Harrison Opera House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "The Tate Pumphouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "CityRange Steakhouse Gril",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "David Burke Prime Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Alexander's Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Morton's The Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Ocean House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Foleys Fish Chop & Steak House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "The Cloverdale Playhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Huntington House Inn",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Main Street Ale House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Eco Schoolhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Sportsman's Warehouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Saltgrass Steak House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "The Chop House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "FireRock Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Cornish Playhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Cowhouse Partners",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Icehouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "9th Street Public House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "House of Brokers Realty, Inc.",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Gravity Taphouse Grille",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Baker Book House Co ",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "The Crush House at Gervasi Vineyard",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Rival House Sporting Parlour",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Poodies Hilltop Roadhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Jim Beam American Stillhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Livingston Parish District Courthouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Lockhorn Cider House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Demeters Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Atlantic House Inn",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Ogunquit Playhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Hanover Street Chophouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Wasabi Japanese Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "The Burger Stand At Taos Ale House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "CC's Coffee House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Mastro's Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Paladino's Pizza House 1647",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "The Clubhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Harry's Roadhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "SONO Field House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Bronx AleHouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Banner Flower House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Mod Coffee House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Off Broadway Shoe Warehouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Firetap Alehouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "The J House ",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Urban Farmer Cleveland's Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "J House Hotel ",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Geneva Chophouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Sullivan's Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Hereford House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Cadillac House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "The Pour House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "WestHouse Hotel New York",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Soho Beach House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Chima Brazilian Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "SugarHouse Casino",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Stone House at Stirling Ridge Restaurant & Events",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Michael Jordan's The Steak House NYC",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Davenport Roadhouse Restaurant and Inn",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Back Forty Texas BBQ Roadhouse & Saloon",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Joyride Taco House East ",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "The Mortuary Haunted House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Brick House Tavern & Tap",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Prime & Provisions Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "801 CHOPHOUSE",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Farraddays Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "The Loeb Boathouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Winspear Opera House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Girin SteakHouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Chophouse Row",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Old Town Pour House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "The Boathouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Winans Chocolates & Coffee House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Mr Crabby’s Seafood House and Sports Bar",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Staplehouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "House of Hoops",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Donovan House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Factotum Brewhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Chianina Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "EcoHouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Ember Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Yard House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Bounce House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Gingerbread House Toy Store",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Joseph Bartholomew Golf Course Clubhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Fleming's Prime Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "DSW Shoe Warehouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Designer Shoe Warehouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Madhouse Team Store",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Aramark/Houston Texans NRG Stadium Club Level",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Minas Brazilian Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Browns Socialhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Beach House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Nestle Toll House Cafe",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Lennox Warehouse ",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Lighthouse Dispensary",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Chateau Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Del Frisco's Double Eagle Steakhouse",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Charley's Steak House Porte-cochere",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Yale University - Charles Henry Farnam House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Yale University - Edwin S. Wheeler House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Hart House",
                    "t": "Brand",
                    "i": 0
                },
                {
                    "countryid": "",
                    "statecode": "",
                    "otherstate": "",
                    "city": "",
                    "streetname": "",
                    "zipcode": "",
                    "username": "",
                    "bizcat": "",
                    "v": "Audemars Piguet - AP House Los Angeles",
                    "t": "Brand",
                    "i": 0
                }
            ],
            "t": "Brand"
        },
        {
            "data": [
                {
                    "countryid": "MYBRXq55cGCCTaW7GlCwbA",
                    "statecode": "NY",
                    "otherstate": "",
                    "city": "NEW YORK",
                    "streetname": "902 Broadwa",
                    "zipcode": "10010",
                    "username": "Charles Gross",
                    "bizcat": "AGENT",
                    "v": "Phipps Houses",
                    "t": "Vendor",
                    "i": 461
                }
            ],
            "t": "Vendor"
        }
    ]
}